version: '3.6'

services:
  api:
    image: quay.io/go-skynet/local-ai:master-cublas-cuda12-ffmpeg
    ports:
      - 8080:8080
    volumes:
      - C:\localai\models:/models:cached
      - C:\localai\images:/tmp/generated/images/
    command: ["/usr/bin/local-ai"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
